// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXWzXKF3TLZ5dWtIV-COo77PG8rTxJDag',
    appId: '1:668759767042:web:c15971683059b6a2fa8f1b',
    messagingSenderId: '668759767042',
    projectId: 'face-log-fb54d',
    authDomain: 'face-log-fb54d.firebaseapp.com',
    storageBucket: 'face-log-fb54d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlAQ2BzzI3sAkzg_wTwR-HGgMeIJ6gKKM',
    appId: '1:668759767042:android:584a66f562bf8eeffa8f1b',
    messagingSenderId: '668759767042',
    projectId: 'face-log-fb54d',
    storageBucket: 'face-log-fb54d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcEOWdSrRxrq7ExIrJaiz9VA7hnBVGc_o',
    appId: '1:668759767042:ios:c0afa55bb3e97a40fa8f1b',
    messagingSenderId: '668759767042',
    projectId: 'face-log-fb54d',
    storageBucket: 'face-log-fb54d.firebasestorage.app',
    iosBundleId: 'com.example.facelog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcEOWdSrRxrq7ExIrJaiz9VA7hnBVGc_o',
    appId: '1:668759767042:ios:c0afa55bb3e97a40fa8f1b',
    messagingSenderId: '668759767042',
    projectId: 'face-log-fb54d',
    storageBucket: 'face-log-fb54d.firebasestorage.app',
    iosBundleId: 'com.example.facelog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXWzXKF3TLZ5dWtIV-COo77PG8rTxJDag',
    appId: '1:668759767042:web:c7fcacd4a56639e7fa8f1b',
    messagingSenderId: '668759767042',
    projectId: 'face-log-fb54d',
    authDomain: 'face-log-fb54d.firebaseapp.com',
    storageBucket: 'face-log-fb54d.firebasestorage.app',
  );
}
